command: ["python", "-m", "server.app"]

source_code_path: "."

# Configure on-behalf-of user authorization
# This allows the app to act with the identity of the authenticated user
scopes:
  - "sql"          # SQL warehouses and query execution
  - "files.files"  # DBFS files and directories

environment:
  - name: DATABRICKS_HOST
    value_from: workspace
  - name: DATABRICKS_PATH
    value_from: workspace
  - name: DATABRICKS_TOKEN
    value_from: pat
  - name: DATABRICKS_APP_PORT
    value_from: app_port