command: ["python", "-m", "server.app"]

source_code_path: "."

# Configure on-behalf-of user authorization
# This allows the app to act with the identity of the authenticated user
scopes:
  - "all-apis"     # Required for model serving endpoints / Foundation Models
  - "sql"          # SQL warehouses and query execution
  - "files.files"  # DBFS files and directories

environment:
  - name: DATABRICKS_HOST
    value_from: workspace
  - name: DATABRICKS_PATH
    value_from: workspace
  # Note: DATABRICKS_TOKEN (PAT) removed to avoid conflict with OAuth
  # The app will use OAuth (service principal) credentials automatically
  # and on-behalf-of user tokens from X-Forwarded-Access-Token header
  - name: DATABRICKS_APP_PORT
    value_from: app_port